baseURL = 'https://peregrineyao-blog.pages.dev/'
languageCode = 'en-us'
title = "Peregrine's Blog"

theme = "PaperMod"

hasCJKLanguage = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    name = "搜索"
    url = "search"
    weight = 10

[[menu.main]]
    name = "归档"
    url = "archives"
    weight = 20

    [params]
    ShowReadingTime = true
    ShowWordCount = true
    ShowPostNavLinks = true # 开启文章底部的“上一篇/下一篇”按钮
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/yoayoayoa"
[[params.socialIcons]]
    name = "email"
    url = "mailto:yaoheng0721@gmail.com"
fuseOpts = { isCaseSensitive = false, shouldSort = true, location = 0, distance = 100, threshold = 0.4, minMatchCharLength = 0, keys = ["title", "permalink", "summary", "content"] }

# Force Rebuild 2026
